[package]
name = "splice-render"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
splice-media.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tempfile.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
