[package]
name = "splice-gc"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
splice-commit.workspace = true
splice-media.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true

[dev-dependencies]
tempfile.workspace = true
